### ISSUE TITLE
Saving package storage

### ISSUE THREAD

**Issue by LostNuke** [Rhydderchc/hive-db#1]
**Is your feature request related to a problem? Please describe.**
The package installs mongoose and sqlite and in the future also redis and other stuff. This will make the size v v v big. Mongoose itself is already really big.

**Describe the solution you'd like**
A solution to this would be removing the packages from the dependencies, so it doesnt install all of them and check for the packages in the types. So for example when you want to mongo, you have to npm i mongoose for it to work and so on.

**Comment by rhygg** [comment]
Thank you for your suggestion. 
It would be a good idea, to cut down the size of the dependencies, although I believe people would really get confused with the installation of the dependencies such as the two we have at present mongoose and better-sqlite3. There are people who would add this up as an issue.
But I will implement this after we get another database into usage, because the current size of our package is pretty low against other npm packages.
Again, thank you and I'm sure to implement this in the future.

**Comment by thetayloredman** [comment]
Or: put adapters as separate modules?

**Comment by rhygg** [comment]
> Or: put adapters as separate modules?

Yeah, good suggestion will apply after the *redis* update!

**Comment by thetayloredman** [comment]
> > Or: put adapters as separate modules?
> 
> Yeah, good suggestion will apply after the _redis_ update!

Inspiration from [JOSH (`@joshdb/core` on npm)](https://npmjs.com/@joshdb/core) which uses "providers" (here they are "adapters") for the underlying DB I/O (For example, [`@joshdb/sqlite` on npm](https://npmjs.com/@joshdb/sqlite))
